# Generated by Django 4.2.5 on 2023-10-14 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="catalog_category",
        ),
        migrations.AlterModelTable(
            name="product",
            table="catalog_product",
        ),
        migrations.AlterModelTable(
            name="productcategories",
            table="catalog_product_categories",
        ),
        migrations.AlterModelTable(
            name="productproperty",
            table="catalog_product_property",
        ),
        migrations.AlterModelTable(
            name="productpropertyvalue",
            table="catalog_product_property_value",
        ),
    ]
