# Generated by Django 4.2.7 on 2024-01-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_category_table_alter_product_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.FileField(
                blank=True, upload_to="products/", verbose_name="Изображение"
            ),
        ),
    ]
