# Generated by Django 4.2.7 on 2024-01-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="product_image",
            field=models.ImageField(
                blank=True,
                upload_to="categories/products",
                verbose_name="Общее изображение для продуктов",
            ),
        ),
    ]
