# Generated by Django 4.2.7 on 2024-01-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_category_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productproperty",
            name="is_sortable",
            field=models.BooleanField(
                default=False, verbose_name="Сортируемое свойство?"
            ),
        ),
    ]
