# Generated by Django 4.2.11 on 2024-05-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_productproperty_is_sortable"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Название формы"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "name",
                    models.CharField(blank=True, max_length=250, verbose_name="ФИО"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=50, verbose_name="Email"),
                ),
                (
                    "question",
                    models.TextField(blank=True, max_length=500, verbose_name="Вопрос"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "db_table": "catalog_form_submission",
                "ordering": ("-created_date",),
            },
        ),
    ]
