# Generated by Django 4.2.13 on 2024-08-14 08:40

import backend.catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_formsubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=500, verbose_name="Порядок"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/",
                        validators=[backend.catalog.models.validate_file_type],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "db_table": "catalog_document",
            },
        ),
        migrations.CreateModel(
            name="ProductDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=500, verbose_name="Порядок"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_documents",
                        to="catalog.document",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_documents",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_product_document",
                "ordering": ("ordering",),
                "unique_together": {("product", "document")},
            },
        ),
        migrations.CreateModel(
            name="CategoryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=500, verbose_name="Порядок"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_documents",
                        to="catalog.category",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_documents",
                        to="catalog.document",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_category_document",
                "ordering": ("ordering",),
                "unique_together": {("category", "document")},
            },
        ),
        migrations.AddField(
            model_name="category",
            name="documents",
            field=models.ManyToManyField(
                related_name="categories",
                through="catalog.CategoryDocument",
                to="catalog.document",
                verbose_name="Документы",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="documents",
            field=models.ManyToManyField(
                related_name="products",
                through="catalog.ProductDocument",
                to="catalog.document",
                verbose_name="Документы",
            ),
        ),
    ]
