# Generated by Django 4.2.13 on 2024-09-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_document_productdocument_categorydocument_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, max_length=3000, verbose_name="Описание"
            ),
        ),
    ]
