# Generated by Django 4.2.16 on 2024-10-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="order",
            field=models.TextField(blank=True, max_length=5000, verbose_name="Заказ"),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="question",
            field=models.TextField(blank=True, max_length=2500, verbose_name="Вопрос"),
        ),
    ]
