# Generated by Django 4.2.16 on 2024-11-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_formsubmission_order_alter_formsubmission_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryProductProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productproperties_through",
                        to="catalog.category",
                    ),
                ),
                (
                    "productproperty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories_through",
                        to="catalog.productproperty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь свойства с категорией",
                "verbose_name_plural": "Связи свойств с категориями",
                "db_table": "catalog_category_product_properties",
                "unique_together": {("category", "productproperty")},
            },
        ),
        migrations.AddField(
            model_name="category",
            name="properties",
            field=models.ManyToManyField(
                through="catalog.CategoryProductProperties",
                to="catalog.productproperty",
                verbose_name="Свойства",
            ),
        ),
    ]
