# Generated by Django 4.2.16 on 2024-11-10 14:48

from django.db import migrations


def copy_properties_categories_forward(apps, schema_editor):
    ProductProperty = apps.get_model("catalog", "ProductProperty")
    CategoryProductProperties = apps.get_model("catalog", "CategoryProductProperties")
    cat_through = ProductProperty.categories.through.objects.all()
    for elem in cat_through:
        CategoryProductProperties.objects.create(productproperty_id=elem.productproperty_id, category_id=elem.category_id)

    cat_through.delete()

def copy_properties_categories_backward(apps, schema_editor):
    ProductProperty = apps.get_model("catalog", "ProductProperty")
    CategoryProductProperties = apps.get_model("catalog", "CategoryProductProperties")
    cat_through = CategoryProductProperties.objects.all()
    for elem in cat_through:
        ProductProperty.categories.through.objects.create(productproperty_id=elem.productproperty_id, category_id=elem.category_id)

    cat_through.delete()


class Migration(migrations.Migration):


    dependencies = [
        ("catalog", "0010_categoryproductproperties_category_properties"),
    ]

    operations = [
        migrations.RunPython(copy_properties_categories_forward, copy_properties_categories_backward),
    ]
