# Generated by Django 4.2.16 on 2024-11-10 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_copy_properties"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productproperty",
            name="categories",
        ),
        migrations.AlterField(
            model_name="categoryproductproperties",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_properties",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="categoryproductproperties",
            name="productproperty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="catalog.productproperty",
            ),
        ),
    ]
